const categorias = [
    { label: "2º Oficial de Náutica (2ON) – Nível 7", value: "2ON" },
    { label: "1º Oficial de Náutica (1ON) – Nível 8", value: "1ON" },
    { label: "Capitão de Cabotagem (CCB) – Nível 9", value: "CCB" },
    { label: "Capitão de Longo Curso (CLC) – Nível 10", value: "CLC" },
    { label: "Mestre de Cabotagem (MCB) – Nível 6", value: "MCB" },
    { label: "Contramestre (CTR) – Nível 5", value: "CTR" },
    { label: "Marinheiro de Convés (MNC) – Nível 4", value: "MNC" },
    { label: "Moço de Convés (MOC) – Nível 3", value: "MOC" },
    { label: "Marinheiro Auxiliar de Convés (MAC) – Nível 2", value: "MAC" },
    { label: "2º Oficial de Máquinas (2OM) – Nível 7", value: "2OM" },
    { label: "1º Oficial de Máquinas (1OM) – Nível 8", value: "1OM" },
    { label: "Oficial Superior de Máquinas (OSM) – Nível 9", value: "OSM" },
    { label: "Condutor de Máquinas (CDM) – Nível 5", value: "CDM" },
    { label: "Marinheiro de Máquinas (MNM) – Nível 4", value: "MNM" },
    { label: "Moço de Máquinas (MOM) – Nível 3", value: "MOM" },
    { label: "Marinheiro Auxiliar de Máquinas (MAM) – Nível 2", value: "MAM" },
    { label: "Cozinheiro (CZA) – Nível 2", value: "CZA" },
    { label: "Taifeiro (TAA) – Nível 2", value: "TAA" },
    { label: "Enfermeiro (ENF) – Nível 5", value: "ENF" },
    { label: "Auxiliar de Saúde (ASA) – Nível 3", value: "ASA" },
    { label: "EBPQ", value: "EBPQ" },
    { label: "ESOP", value: "ESOP" },
    { label: "ESOQ", value: "ESOQ" },
    { label: "EBGL", value: "EBGL" },
    { label: "ESOG", value: "ESOG" },
    { label: "EPOR", value: "EPOR" },
    { label: "EPOE", value: "EPOE" },
    { label: "ECIA", value: "ECIA" },
    { label: "EGPO", value: "EGPO" },
    { label: "EROG", value: "EROG" },
    { label: "ENET", value: "ENET" },
    { label: "EARP", value: "EARP" },
    { label: "EOPN", value: "EOPN" },
    { label: "EOCA", value: "EOCA" },
    { label: "ESCM", value: "ESCM" },
    { label: "EPSM", value: "EPSM" },
    { label: "BRM", value: "BRM" },
    { label: "CFPN", value: "CFPN" },
    { label: "EGPM", value: "EGPM" },
    { label: "TBS1", value: "TBS1" },
    { label: "EESS", value: "EESS" },
    { label: "EERR", value: "EERR" },
    { label: "Alta Tensão Operacional", value: "ATO" },
    { label: "Alta Tensão Gerência", value: "ATG" },
    { label: "EFOMM – Escola de Formação de Oficiais da Marinha Mercante", value: "EFOMM" },
    { label: "ASON – Adaptação ao Segundo Oficial de Náutica", value: "ASON" },
    { label: "ASOM – Adaptação ao Segundo Oficial de Máquinas", value: "ASOM" },
    { label: "ACON-B – Acesso ao 2º Oficial de Náutica - Básico", value: "ACON-B" },
    { label: "ACON-C – Acesso ao 2º Oficial de Náutica - Complementar", value: "ACON-C" },
    { label: "ACOM-B – Acesso ao 2º Oficial de Máquinas - Básico", value: "ACOM-B" },
    { label: "ACOM-C – Acesso ao 2º Oficial de Máquinas - Complementar", value: "ACOM-C" },
    { label: "CFAQ – Curso de Formação de Aquaviários", value: "CFAQ" },
    { label: "CAAQ – Curso de Adaptação para Aquaviários", value: "CAAQ" }
]

export default categorias;
